site_name: Kumquat Documentation
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
nav:
  - 'quickstart.md'
  - 'buildroot-setup.md'
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition