site_name: Kumquat Documentation
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
  - include_dir_to_nav:
    sort_file: true
    sort_directory: true
nav:
  - 'quickstart.md'
  - 'buildroot-setup.md'
  - Interfaces: 'interfaces/'
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - tables